spring:
  main:
    log-startup-info: false
    banner-mode: off
    web-application-type: none
  application:
    name: mono-cli
logging:
  level:
    org.springframework: error
mono:
  x-token: ${MONO_TOKEN:}
  transaction-limit: 500
