spring:
  main:
    log-startup-info: false
    banner-mode: off
  application:
    name: mono-cli
mono:
  x-token: ${MONO_TOKEN:}
  endpoints:
    base-url: https://api.monobank.ua
    currency: ${mono.endpoints.base-url}/bank/currency
    client-info: ${mono.endpoints.base-url}/personal/client-info
    statement: ${mono.endpoints.base-url}/personal/statement/{account}/{from}/{to}
